package engine

// SprigFunctions contains documentation and signatures for built-in Helm/Sprig template functions.
var SprigFunctions = map[string]string{
	"dict":     "**dict** `(dict \"key1\" \"value1\" \"key2\" \"value2\" ...)`\n\nCreates a dictionary from a list of keys and values.",
	"default":  "**default** `(default DEFAULT_VALUE GIVEN_VALUE)`\n\nReturns `DEFAULT_VALUE` if `GIVEN_VALUE` is empty, otherwise returns `GIVEN_VALUE`.",
	"trunc":    "**trunc** `(trunc LENGTH STRING)`\n\nTruncates a string to the given length.",
	"trimAll":  "**trimAll** `(trimAll CHARACTER STRING)`\n\nRemoves all occurrences of the given character from the string.",
	"nindent":  "**nindent** `(nindent COUNT STRING)`\n\nIndents `STRING` by `COUNT` spaces and prepends a newline.",
	"indent":   "**indent** `(indent COUNT STRING)`\n\nIndents `STRING` by `COUNT` spaces.",
	"empty":    "**empty** `(empty VALUE)`\n\nReturns true if the value is considered empty.",
	"fail":     "**fail** `(fail MESSAGE)`\n\nUnconditionally returns an error with the given message.",
	"coalesce": "**coalesce** `(coalesce VALUE1 VALUE2 ...)`\n\nReturns the first non-empty value.",
	"toYaml":   "**toYaml** `(toYaml VALUE)`\n\nConverts the given value to a YAML string.",
	"fromYaml": "**fromYaml** `(fromYaml STRING)`\n\nParses a YAML string into a dictionary/list.",
	"toJson":   "**toJson** `(toJson VALUE)`\n\nConverts the given value to a JSON string.",
	"fromJson": "**fromJson** `(fromJson STRING)`\n\nParses a JSON string into a dictionary/list.",
	"b64enc":   "**b64enc** `(b64enc STRING)`\n\nEncodes the string as base64.",
	"b64dec":   "**b64dec** `(b64dec STRING)`\n\nDecodes a base64 string.",
	"quote":    "**quote** `(quote STRING)`\n\nWraps a string in double quotes.",
	"squote":   "**squote** `(squote STRING)`\n\nWraps a string in single quotes.",
	"upper":    "**upper** `(upper STRING)`\n\nConverts a string to uppercase.",
	"lower":    "**lower** `(lower STRING)`\n\nConverts a string to lowercase.",
	"replace":  "**replace** `(replace OLD NEW STRING)`\n\nReplaces all occurrences of `OLD` with `NEW` in `STRING`.",
	"tpl":      "**tpl** `(tpl TEMPLATE_STRING CONTEXT)`\n\nEvaluates a string as a Helm template.",
	"include":  "**include** `(include \"TEMPLATE_NAME\" CONTEXT)`\n\nExecutes the named template and returns the output as a string (can be piped).",
	"template": "**template** `(template \"TEMPLATE_NAME\" CONTEXT)`\n\nExecutes the named template inline (cannot be piped).",
	"printf":   "**printf** `(printf FORMAT_STRING VALUES...)`\n\nFormats string using standard Go formatting verbs like `%s`, `%d`.",
	"eq":       "**eq** `(eq VAL1 VAL2)`\n\nReturns true if VAL1 == VAL2.",
	"ne":       "**ne** `(ne VAL1 VAL2)`\n\nReturns true if VAL1 != VAL2.",
	"lt":       "**lt** `(lt VAL1 VAL2)`\n\nReturns true if VAL1 < VAL2.",
	"le":       "**le** `(le VAL1 VAL2)`\n\nReturns true if VAL1 <= VAL2.",
	"gt":       "**gt** `(gt VAL1 VAL2)`\n\nReturns true if VAL1 > VAL2.",
	"ge":       "**ge** `(ge VAL1 VAL2)`\n\nReturns true if VAL1 >= VAL2.",
	"not":      "**not** `(not VAL)`\n\nNegates the boolean value.",
	"and":      "**and** `(and VAL1 VAL2 ...)`\n\nLogical AND.",
	"or":       "**or** `(or VAL1 VAL2 ...)`\n\nLogical OR.",
	"hasKey":   "**hasKey** `(hasKey DICT KEY)`\n\nReturns true if the dictionary has the given key.",
	"keys":     "**keys** `(keys DICT)`\n\nReturns a list of all keys in one or more dictionaries.",
	"values":   "**values** `(values DICT)`\n\nReturns a list of all values in a dictionary.",
	"pluck":    "**pluck** `(pluck KEY DICT1 DICT2 ...)`\n\nExtracts a list of values belonging to the given key across multiple dictionaries.",
	"merge":    "**merge** `(merge DEST SRC)`\n\nMerges two dictionaries (modifies DEST in place).",
	"list":     "**list** `(list VAL1 VAL2 ...)`\n\nCreates a list of values.",
	"append":   "**append** `(append LIST VAL)`\n\nAppends a value to a list.",
	"prepend":  "**prepend** `(prepend LIST VAL)`\n\nPrepends a value to a list.",
	"first":    "**first** `(first LIST)`\n\nReturns the first item of a list.",
	"last":     "**last** `(last LIST)`\n\nReturns the last item of a list.",
	"title":    "**title** `(title STRING)`\n\nConverts a string to title case.",
	"untitle":  "**untitle** `(untitle STRING)`\n\nRemoves title casing.",
	"repeat":   "**repeat** `(repeat COUNT STRING)`\n\nRepeats a string multiple times.",
	"if":       "**if** `{{ if PIPELINE }} T1 {{ end }}`\n\nIf the value of the pipeline is empty, no output is generated; otherwise, T1 is executed. The empty values are false, 0, any nil pointer or interface value, and any array, slice, map, or string of length zero.",
	"else":     "**else** `{{ else if PIPELINE }} T2 {{ else }} T3 {{ end }}`\n\nFallback execution for `if` or `with` blocks.",
	"with":     "**with** `{{ with PIPELINE }} T1 {{ end }}`\n\nIf the value of the pipeline is not empty, dot (.) is set to that value and T1 is executed. Otherwise, no output is generated.",
	"range":    "**range** `{{ range PIPELINE }} T1 {{ end }}`\n\nThe value of the pipeline must be an array, slice, map, or channel. If the value of the pipeline has length zero, nothing is output; otherwise, dot is set to the successive elements of the array, slice, or map and T1 is executed.",
	"end":      "**end** `{{ end }}`\n\nTerminates a block (if, with, range, define).",
	"define":   "**define** `{{ define \"name\" }} T1 {{ end }}`\n\nDefines a template that can be executed later via `include` or `template`.",
}
